import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { ArrowRight, Target, BookOpen, BarChart3, Clock, Sparkles, TrendingUp, ChevronRight } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollReveal from "@/components/ScrollReveal";
import { careers } from "@/data/careers";
import heroImage from "@/assets/hero-illustration.jpg";

const features = [
  {
    icon: Target,
    title: "Career Discovery",
    description: "Explore hundreds of career paths with AI-powered recommendations tailored to your interests and strengths.",
  },
  {
    icon: Sparkles,
    title: "AI Skill Roadmaps",
    description: "Get personalized learning paths generated by AI that map exactly what skills you need and in what order.",
  },
  {
    icon: BookOpen,
    title: "Curated Resources",
    description: "Access hand-picked courses, tutorials, and materials ranked by quality and relevance to your roadmap.",
  },
  {
    icon: Clock,
    title: "Smart Scheduling",
    description: "Adaptive time management that fits learning into your life with intelligent task prioritization.",
  },
  {
    icon: BarChart3,
    title: "Progress Analytics",
    description: "Track your growth with visual dashboards showing skill acquisition, milestones, and time invested.",
  },
  {
    icon: TrendingUp,
    title: "Market Intelligence",
    description: "Stay aligned with industry demand through real-time labor market data and trending skill insights.",
  },
];

const steps = [
  { number: "01", title: "Explore Careers", description: "Browse our intelligent career catalog. Filter by interests, skills, or industry to discover paths you never knew existed." },
  { number: "02", title: "Get Your Roadmap", description: "Select a career and our AI instantly generates a complete skill development roadmap with milestones and timelines." },
  { number: "03", title: "Learn & Track", description: "Follow your personalized path with curated resources. Track every skill mastered and see your progress in real-time." },
];

const stats = [
  { value: "847", label: "Career paths mapped" },
  { value: "12.4k", label: "Skills cataloged" },
  { value: "3.2k", label: "Curated resources" },
  { value: "94%", label: "User satisfaction" },
];

const LandingPage = () => {
  return (
    <div className="min-h-screen bg-background overflow-hidden">
      <Navbar />

      {/* Hero */}
      <section className="pt-28 pb-20 lg:pt-36 lg:pb-28 relative">
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-40 -right-40 w-[600px] h-[600px] rounded-full bg-primary/5 blur-3xl" />
          <div className="absolute top-20 -left-20 w-[400px] h-[400px] rounded-full bg-accent/5 blur-3xl" />
        </div>
        <div className="container mx-auto px-4 lg:px-8 relative">
          <div className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
            <div>
              <div className="animate-fade-up">
                <span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary text-sm font-medium mb-6">
                  <Sparkles className="w-3.5 h-3.5" />
                  AI-Powered Career Intelligence
                </span>
              </div>
              <h1 className="animate-fade-up font-display text-4xl sm:text-5xl lg:text-6xl font-bold leading-[1.08] mb-6 text-balance" style={{ animationDelay: "80ms" }}>
                Navigate your career with{" "}
                <span className="gradient-text">clarity and confidence</span>
              </h1>
              <p className="animate-fade-up text-lg text-muted-foreground max-w-lg mb-8 text-pretty leading-relaxed" style={{ animationDelay: "160ms" }}>
                SkillPath AI transforms career confusion into a clear, actionable roadmap. Discover professions, master skills, and track your journey — all powered by AI.
              </p>
              <div className="animate-fade-up flex flex-wrap gap-3" style={{ animationDelay: "240ms" }}>
                <Button variant="hero" size="xl" asChild>
                  <Link to="/explore">
                    Find My Dream Career <ArrowRight className="w-5 h-5 ml-2" />
                  </Link>
                </Button>
                <Button variant="hero-outline" size="xl" asChild>
                  <Link to="/dashboard">Go to Dashboard</Link>
                </Button>
              </div>
            </div>
            <div className="animate-fade-up relative" style={{ animationDelay: "300ms" }}>
              <div className="relative rounded-2xl overflow-hidden shadow-2xl shadow-primary/10">
                <img src={heroImage} alt="AI-powered career visualization" className="w-full h-auto" />
                <div className="absolute inset-0 bg-gradient-to-t from-background/20 to-transparent" />
              </div>
              <div className="absolute -bottom-4 -left-4 glass rounded-xl px-4 py-3 shadow-lg animate-float">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-lg gradient-bg flex items-center justify-center">
                    <TrendingUp className="w-4 h-4 text-primary-foreground" />
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Skill Progress</p>
                    <p className="text-sm font-semibold">+27% this month</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="py-12 border-y border-border bg-surface/50">
        <div className="container mx-auto px-4 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, i) => (
              <ScrollReveal key={stat.label} delay={i * 80} className="text-center">
                <p className="font-display text-3xl lg:text-4xl font-bold text-foreground">{stat.value}</p>
                <p className="text-sm text-muted-foreground mt-1">{stat.label}</p>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20 lg:py-28">
        <div className="container mx-auto px-4 lg:px-8">
          <ScrollReveal className="text-center max-w-2xl mx-auto mb-16">
            <h2 className="font-display text-3xl lg:text-4xl font-bold mb-4 text-balance">
              Everything you need to launch your career
            </h2>
            <p className="text-muted-foreground text-lg text-pretty">
              From discovery to job-readiness, SkillPath AI covers every stage of your professional journey.
            </p>
          </ScrollReveal>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, i) => (
              <ScrollReveal key={feature.title} delay={i * 80} direction="scale">
                <div className="group p-6 rounded-2xl bg-card border border-border card-hover h-full">
                  <div className="w-11 h-11 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/15 transition-colors">
                    <feature.icon className="w-5 h-5 text-primary" />
                  </div>
                  <h3 className="font-display text-lg font-semibold mb-2">{feature.title}</h3>
                  <p className="text-muted-foreground text-sm leading-relaxed">{feature.description}</p>
                </div>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 lg:py-28 bg-surface/50">
        <div className="container mx-auto px-4 lg:px-8">
          <ScrollReveal className="text-center max-w-2xl mx-auto mb-16">
            <h2 className="font-display text-3xl lg:text-4xl font-bold mb-4">How it works</h2>
            <p className="text-muted-foreground text-lg">Three steps to career clarity. No guesswork required.</p>
          </ScrollReveal>

          <div className="grid md:grid-cols-3 gap-8 lg:gap-12">
            {steps.map((step, i) => (
              <ScrollReveal key={step.number} delay={i * 120} direction={i === 0 ? "right" : i === 2 ? "left" : "up"}>
                <div className="relative">
                  <span className="font-display text-6xl lg:text-7xl font-bold text-primary/10">{step.number}</span>
                  <h3 className="font-display text-xl font-semibold mt-2 mb-3">{step.title}</h3>
                  <p className="text-muted-foreground leading-relaxed">{step.description}</p>
                </div>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      {/* Popular Careers */}
      <section className="py-20 lg:py-28 bg-surface/30 border-y border-border">
        <div className="container mx-auto px-4 lg:px-8">
          <ScrollReveal className="text-center max-w-2xl mx-auto mb-16">
            <h2 className="font-display text-3xl lg:text-4xl font-bold mb-4">
              Explore Popular Career Paths
            </h2>
            <p className="text-muted-foreground text-lg">
              Jump directly into the most in-demand roles with tailored skill roadmaps.
            </p>
          </ScrollReveal>

          <div className="grid md:grid-cols-3 gap-6">
            {careers.map((career, i) => (
              <ScrollReveal key={career.id} delay={i * 100} direction="up">
                <div className="group p-6 rounded-2xl bg-card border border-border card-hover flex flex-col h-full shadow-sm">
                  <div className="mb-4">
                    <h3 className="font-display text-2xl font-bold">{career.name}</h3>
                    <p className="text-muted-foreground text-sm mt-3 leading-relaxed line-clamp-3">
                      {career.description}
                    </p>
                  </div>
                  <div className="mt-auto pt-5 flex items-center justify-between border-t border-border/60">
                    <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      {career.roadmap.reduce((acc, p) => acc + p.skills.length, 0)} Skills
                    </span>
                    <Button variant="ghost" size="sm" className="text-primary hover:text-primary hover:bg-primary/10 -mr-3" asChild>
                      <Link to={`/roadmap/${career.id}`}>View Roadmap <ArrowRight className="w-4 h-4 ml-1.5" /></Link>
                    </Button>
                  </div>
                </div>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 lg:py-28">
        <div className="container mx-auto px-4 lg:px-8">
          <ScrollReveal>
            <div className="gradient-bg rounded-3xl p-10 lg:p-16 text-center relative overflow-hidden">
              <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(255,255,255,0.08),transparent)] pointer-events-none" />
              <div className="relative">
                <h2 className="font-display text-3xl lg:text-4xl font-bold text-primary-foreground mb-4 text-balance">
                  Ready to find your path?
                </h2>
                <p className="text-primary-foreground/80 text-lg max-w-lg mx-auto mb-8">
                  Join thousands of learners who turned career uncertainty into a structured journey toward their dream job.
                </p>
                <Button size="xl" variant="secondary" className="font-semibold text-foreground" asChild>
                  <Link to="/explore">
                    Explore Careers Now <ChevronRight className="w-5 h-5" />
                  </Link>
                </Button>
              </div>
            </div>
          </ScrollReveal>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default LandingPage;
